# /etc/zsh/zshenv: system-wide .zshenv file for zsh.
#
# This file is sourced on all invocations of the shell.
# If the -f flag is present or if the NO_RCS option is
# set within this file, all other initialization files
# are skipped.
#
# This file should contain commands to set the command
# search path, plus other important environment variables.
# This file should not contain commands that produce
# output or assume the shell is attached to a tty.
#
# Global Order: zshenv, zprofile, zshrc, zlogin

# Set user based on UID
export USER=$([[ "$(print -P "%#")" == '#' ]] && print 'root' || print 'system')

# Home directory
export HOME=/data/local

# Dynamically set HOST to Android codename and ANDROID_ROOT
export HOST="android"
export ANDROID_ROOT=/

# Android-specific directories
export ANDROID_DATA=/data

# Locale settings
export LC_ALL="C"
export LANGUAGE="C"
export LOGNAME=$USER

# Shell settings
export SHELL=zsh

# History settings
export HISTFILE=${HOME}/.zsh_history
setopt HIST_FCNTL_LOCK  # Lock history file for safety

# Terminal settings
export TERMINFO=/system/usr/share/terminfo
export TERM=xterm-256color

# Temporary files directory
export TMPPREFIX=${HOME}/tmp
