# /etc/zsh/zshrc: system-wide .zshrc file for zsh(1).
#
# This file is sourced only for interactive shells. It
# should contain commands to set up aliases, functions,
# options, key bindings, etc.
#
# Global Order: zshenv, zprofile, zshrc, zlogin

fetch-zshrc() {
    busybox wget -O $HOME/.zshrc https://raw.githubusercontent.com/rhythmcache/zsh-for-android/main/zsh/.zshrc
}
